spring.application.name=paseadores

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}

jwt.secret=${JWT_SECRET:dev-secret-key-123456789}

logging.level.org.springframework.security=DEBUG